version: '2'

services:
  keycloak:
      image: devplant/chat-keycloak
      environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        KEYCLOAK_IMPORT: /opt/jboss/hacktalks-realm.json
        
  mongo:
    image: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always

  chat-frontend:
    image: devplant/chat-frontend
    restart: always

  chat-backend:
    image: devplant/chat-backend
    restart: always  
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MONGO_URL: mongodb://mongo:27017/chat    
      AUTH_SERVER_URL: http://auth.devplant.ro/auth    