version: '3'

services:
  keycloak:
      image: jboss/keycloak
      environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      ports:
        - 8080:8080

  mongo:
    image: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

  chat-frontend:
    image: devplant/chat-frontend
    restart: always
    ports:
      - 8180:8080

  chat-backend:
    image: devplant/chat-backend
    restart: always  
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MONGO_URL: mongodb://mongo:27017/chat    
      AUTH_SERVER_URL: http://10.0.1.9:8080/auth    