version: '3'

services:
  keycloak:
      image: devplant/chat-keycloak
      environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      ports:
        - 8080:8080
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
